- Project.toml
- src/PowerSimulationsDynamics.jl
- src/base/definitions.jl
- src/base/ports.jl
- src/base/simulation.jl
- test/Project.toml
- test/data_tests/OMIB.raw
- test/data_tests/test01.jl
- test/test_base.jl
> Misc Improvements

- test/data_tests/test14.jl
> update branch name

- docs/src/component_models/freq_esti.md
- docs/src/component_models/network.md
- docs/src/component_models/outer_control.md
- src/models/device.jl
- src/models/inverter_models/DCside_models.jl
The following PR closes #49 and #51.
In addition, add documentation for `FixedFrequency` PLL and `ActivePowerDroop` outer control model.
> Fix some issues and update docs

- src/base/simulation_initialization.jl
fix for `get_initial_conditions` function
> Fix get initial conditions

- src/base/simulation_initialization.jl
- src/models/generator_models/machine_models.jl
- src/models/saturation_models.jl
- src/models/system.jl
- test/data_tests/test07.jl
- test/test_case20_ac1a.jl
- test/test_case21_gast.jl
- test/test_case22_SteamTurbineGov1.jl
- test/test_case25_multimach_dynlines.jl
Patches partially the dual number issue.
> patch to dual issue 

- src/PowerSimulationsDynamics.jl
- src/base/definitions.jl
- src/base/device_indexing.jl
- src/base/perturbations.jl
- src/base/simulation_inputs.jl
- src/initialization/init_device.jl
- src/models/source_models.jl
- test/test_case27_source_bus_voltage_change.jl
Adding a custom perturbation to change the source bus voltage. Added test 27 to test new perturbation.
> Adding perturbation to change source bus voltage

- src/PowerSimulationsDynamics.jl
- src/post_processing/post_proc_common.jl
- src/utils/plot_utils.jl
- test/test_case24_gridfollowing.jl
Similar to `get_activepower_series` and `get_reactivepower_series` but returns real and imaginary currents.
> Add functions to get current of device in system base

- src/base/definitions.jl
- src/base/nlsolve_wrapper.jl
- src/base/simulation_initialization.jl
- src/initialization/init_device.jl
- src/initialization/inverter_components/init_frequency_estimator.jl
- src/initialization/inverter_components/init_inner.jl
- src/initialization/inverter_components/init_outer.jl
@m-bossart this PR partially fixes the mismatches we see with the PVS. It also add some additional code to check for incorrect initialization that might "self-correct"
> fix droop control bug

- docs/make.jl
- docs/src/quick_start_guide.md
- src/PowerSimulationsDynamics.jl
- src/base/simulation.jl
- src/base/simulation_initialization.jl
- src/base/simulation_inputs.jl
- test/test_base.jl
- test/test_case11_dynbranches.jl
Closes #134 
Closes #133 
Closes #132
> Add additional features and minor fixes

- docs/src/perturbations.md
> Fix docs placeholder

- src/PowerSimulationsDynamics.jl
- src/base/definitions.jl
- src/base/jacobian.jl
- src/base/simulation.jl
- src/base/simulation_initialization.jl
- src/base/small_signal.jl
- test/test_base.jl
closes #143 
This function now allows to get the Jacobian function and disentangles the small signal analysis from the simulation 
cc. @cuihantao this is the feature you requested.
> jacobian access

- docs/src/execute.md
- docs/src/small.md
> add get jacobian docs

- src/models/saturation_models.jl
Fix upper limit check in `output_pss_limiter`.
> Limit check bug in output_pss_limiter

- src/base/device_wrapper.jl
- src/base/simulation_inputs.jl
- test/performance/performance_test.jl
Temporary solution for continuing surrogate development with current `DynamicWrapper`
> add ext to dynamic wrapper

- src/base/device_wrapper.jl
- test/test_base.jl
> Error when Classic Machine is used with AVR

- src/PowerSimulationsDynamics.jl
- src/base/simulation_results.jl
- src/post_processing/post_proc_generator.jl
- src/post_processing/post_proc_inverter.jl
- src/post_processing/post_proc_source.jl
- test/test_case02_oneDoneQ.jl
- test/test_case13_avrs.jl
- test/test_case14_inverter_ref.jl
- test/test_case21_gast.jl
- test/test_case22_SteamTurbineGov1.jl
- test/test_case31_hygov.jl
TODO: Tests in PSS/E for HYGOV, GAST and TGOV1.
Closes #247
> Add post processing of mechanical torque and source current

- src/PowerSimulationsDynamics.jl
- src/base/simulation_results.jl
- test/test_case26_SEXS.jl
I'm installing PSSE to validate the test case 26 line flows.
> Add series branch flow

- src/initialization/generator_components/init_avr.jl
- src/models/generator_models/avr_models.jl
Adding SCRX model (init, mass matrix and model, need to debug instability)
> AVR functions (SCRX model) 

- src/base/simulation_inputs.jl
- src/post_processing/post_proc_source.jl
Also fixes a small typo in generating simulation inputs for a system with no branches.
> Post process output current for PeriodicVariableSource

- src/base/simulation.jl
- Updates checking for successful retcode per: https://docs.sciml.ai/SciMLBase/stable/interfaces/Solutions/#retcodes
- Was having issues where the retcode was Success but the simulation was failing (the check wasn't working properly).
> change retcode handling

- src/models/common_controls.jl
Hello, I'm adding the Ramp Tracking Filter Block, and the Lead-Lag Blocks from 3rd to 8th order that it requires
> Ramp tracking filter
