NREL-Sienna/PowerSimulationsDynamics.jl

docs/src/reference_frames.md

In the documentation of the reference frames there is an imaginary unit missing in the exponent of the complex representation.

Missing imaginary unit in the docs

---

docs/src/component_models/freq_esti.md
docs/src/component_models/outer_control.md
src/base/simulation_initialization.jl

The following PR attempts to fix the following issues:
- If the NLsolve call never converged, but it always has finite values, it get stuck in a loop infinitely. This was repaired by changing Line 105 to `BUILD_FAILED`.
- Now we iterate through solvers and tolerances. For the generic renewable models I'm having troubles converging without using newton, so now it tests using `:trust_region` and `:newton`.
- There was a bug about warning after everything fails. The comment about that the Simulation might diverge must be done after passing through all the loop of solvers and tolerances.

Update simulation initialization call

---

src/initialization/init_device.jl

Missing `sqrt` call in dynamic branch initialzation.
Perhaps this pattern should be replaced with [hypot](http://www.jlhub.com/julia/manual/en/function/hypot).

Small fix to init_device.jl branch initialzation

---

src/base/simulation_initialization.jl

Variable `p` is not defined for string formatting in `check_valid_values`.
Is `i` undefined at this point?
https://github.com/rwl/PowerSimulationsDynamics.jl/blob/bc9b33c75d3176933d91a57fa05bf905c5619843/src/base/simulation_initialization.jl#L141

Small fix to string formatting in check_valid_values

---

src/base/perturbations.jl
src/base/simulation_inputs.jl
src/models/branch.jl
src/models/dynline_model.jl

@rodrigomha this PR enables using the same series branch model from the line for the transformers and adds a method to implement in a later stage the L shape model. 
We currently can't implement the L-shape model due to some limitations in `PowerSystems.jl`. This PR requires upstream PSY and PFS PRs merged

add methods for dynamic transformers

---

src/PowerSimulationsDynamics.jl
src/base/device_wrapper.jl
src/base/jacobian.jl
src/base/model_validation.jl
src/base/nlsolve_wrapper.jl
src/base/simulation_inputs.jl
test/test_base.jl

closes #263 
closes #206 -> only prints NLsolve trace if the logging level for console is above Info. 
We need to review the other not allowed combinations, we had some for the REGC_A

Inverter validation and silent mode

---

src/base/simulation_results.jl
src/post_processing/post_proc_inverter.jl

Allows post-processing of system frequency to post-process the frequency of certain devices (e.g. VOC inverter)
resolves #281

Post processes system frequency 

---

src/initialization/init_device.jl
src/models/device.jl
src/post_processing/post_proc_generator.jl
test/test_case42_dera.jl

The change include an error for DynamicInjection cases.

Update DERA output and minor fixes

---

src/initialization/init_device.jl

Tests pass after removing the duplicate call to` initailize_converter!`. I think this might just be a bug?

remove duplicate initialize_converter!

---

src/base/device_wrapper.jl
src/base/simulation.jl
src/initialization/generator_components/init_tg.jl

Adds an ext field to StaticWrapper. The reason for this change is to allow for implementing new surrogate models which are `<:StaticInjection` with minimal changes to PSID.  Also creates a function  `_add_callback!` to allow for handling different types of perturbations when building the callback vector. In my case this allows me to define a perturbation which is essentially just for saving values during the simulation.

add ext to StaticWrapper

---

src/base/device_wrapper.jl
src/base/perturbations.jl
src/base/simulation_inputs.jl
src/initialization/generator_components/init_tg.jl
test/test_case50_load_basepower.jl

- Scales the base power for loads so that the base power of the load can be different than the system base. 
- Test includes a simulation with `LoadTrip `and `LoadChange` to ensure the scaling is handled in the perturbations as well.

fix basepower scaling in loads

---

docs/src/perturbations.md
docs/src/tutorials/tutorial_inverter_modeling.md

fix docs issues

---

src/base/jacobian.jl

For generating datasets from PSID simulations it is useful to rely on a seed and random number generator to randomly select a perturbation. Currently, it is not possible to evaluate the same set of randomly selected perturbations for systems of different size (# of states) because of the call to the random number generator within a PSID simulation. This PR will reset the state of the random number generator so the state is not changed during a simulation.

restore RNG state after generating random numbers

---

src/base/simulation.jl

Fixes swapped descriptions of `Simulation!` and `Simulation `

Fix docs typo

---

src/base/simulation_results.jl
src/post_processing/post_proc_generator.jl
src/post_processing/post_proc_inverter.jl
src/post_processing/post_proc_loads.jl
src/post_processing/post_proc_source.jl
test/test_base.jl

Expands the interface to allow for passing a vector of times instead of simply a fixed dt or nothing which returns the solution timesteps.

Access solution at arbitrary vector of times

---

src/base/simulation_inputs.jl

When creating the range for inner vars for dynamic injectors, the ranges for distinct devices are overlapped by one. The tests still pass because in practice the first/last inner var for certain devices could be unused.

inner vars indexing bug

---

src/base/simulation_results.jl
test/test_base.jl

The post processing functions did not return Vector{Float64} when dt was passed. This makes the output the same regardless of dt being specified or not.

post processing functions return Vector{Float64}

---

src/base/simulation.jl

this way, partial results are still visible, which can be helpful for analysis.

save results even if simulation failed

---

src/base/jacobian.jl
test/test_base.jl
test/utils/data_utils.jl

Added a test for getting the Jacobian with ` sparse_retrive_loop >0` which would have hit this bug. 
Can use this system when ready instead of manually building the system: NREL-Sienna/PowerSystemCaseBuilder.jl#99

Fixes a bug when calling Jacobian for a system with delays

---

README.md

I also updated the about section

Add Documentation text in README
